### ISSUE TITLE
ds_generator crashed

### ISSUE THREAD

**Issue by Oxygen-Chu** [UCLA-VAST/AutoDSE#3]
I see the ds_generator crashed with simple demo.
![image](https://user-images.githubusercontent.com/22520522/161925760-111eda3f-74c2-4fef-8269-cabcb0afc8cd.png)

![image](https://user-images.githubusercontent.com/22520522/161925895-5e1619c4-095a-4f33-a24b-aeda10b7059d.png)

**Comment by atefehsz** [comment]
You need to use `#pragma ACCEL kernel` on top of your kernel's top function. Also, do not include any optimization pragmas in the code. If you want to manually set some pragmas, do it after `ds_generator` is done (Once `ds_generator` generated the design space, edit/add any pragmas you want on the resulting code).

**Comment by Oxygen-Chu** [comment]
is there a  detailed explanation for AutoDSE usage?
I hardly find any.

**Comment by atefehsz** [comment]
All you need to know for working with AutoDSE is there on the [tutorial page](https://ucla-vast.github.io/AutoDSE/). As long as your project directory is runnable by the Merlin Compiler (you can check this by running `make mcc_estimate` in your project directory), AutoDSE can work for you. If you want AutoDSE to generate the design space, then it needs to get the plain C code.
