### ISSUE TITLE
Problem when executing docker-build.sh

### ISSUE THREAD

**Issue by nibst** [UCLA-VAST/AutoDSE#5]
Hi, i'm getting this problem when I try to execute docker-build.sh:

Step 1/23 : FROM merlin:latest as builder
pull access denied for merlin, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

I'm logged into docker, so it seems that the image doesnt exists on DockerHub or something.

**Comment by atefehsz** [comment]
Please note that you should install the Merlin Compiler before using AutoDSE as mentioned [here](https://github.com/UCLA-VAST/AutoDSE#development-requirements). We assume that Merlin is already installed in a docker on your system. If you installed it locally, you can run the commands in the [Dockerfile](https://github.com/UCLA-VAST/AutoDSE/blob/main/docker/Dockerfile) directly on your server.
