### ISSUE TITLE
error when run ./docker-build.sh

### ISSUE THREAD

**Issue by alienwan34** [UCLA-VAST/AutoDSE#7]
![error](https://user-images.githubusercontent.com/18711612/227170665-7f31c451-d1f3-446e-b730-fac5c8cb7513.png)

ERROR: failed to solve: merlin:latest: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

**Comment by atefehsz** [comment]
Please follow the instructions in the README, you need to install Merlin first.

**Comment by alienwan34** [comment]
thx very much，i have successfully invoke AutoDSE in docker, but i don't know how to run AutoDSE . It's difficult to understand the parameters of each command (autodse/dse/ds_generator). Is there a tutorial for AutoDSE ?
![1679639472697](https://user-images.githubusercontent.com/18711612/227443131-a0bb22f6-2108-4684-892d-ad25638da6c4.png)

**Comment by alienwan34** [comment]
Could you please give me an example  running AutoDSE.
